version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: food-ordering-service-db
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  php_fpm:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/
    container_name: food-ordering-service-php
    depends_on:
      - mysql
    networks:
      - laravel

  nginx_url:
    image: nginx:latest
    container_name: food-ordering-service-nginx
    networks:
      - laravel
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_fpm
      - mysql
    ports:
      - "80:80"

networks:
  laravel:
    driver: bridge